name: TF Test
description: |
  Reusable GitHub Action to test Terraform/OpenTofu modules.
  AWS role ARN can be provided either:
  1. As an input parameter (aws_role_arn) - takes precedence
  2. As an environment variable (TF_TEST_AWS_ROLE_ARN)
author: hello@masterpoint.io
inputs:
  tf_type:
    required: true
    description: Type of terraform to use (tofu or terraform)
  aws_role_arn:
    required: false
    description: AWS role ARN to assume for testing (takes precedence over TF_TEST_AWS_ROLE_ARN env var)
  aws_region:
    required: false
    default: us-east-1
    description: AWS region to use
  github_token:
    required: true
    description: GitHub token for checkout
  role_session_name:
    required: false
    default: GitHubActions-TF-Test
    description: AWS role session name for OIDC authentication

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.3
      with:
        token: ${{ inputs.github_token }}

    - name: Aqua Cache
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      if: ${{ !github.event.act }}
      with:
        path: ~/.local/share/aquaproj-aqua
        key: v1-aqua-installer-${{runner.os}}-${{runner.arch}}-${{hashFiles('aqua.yaml')}}
        restore-keys: |
          v1-aqua-installer-${{runner.os}}-${{runner.arch}}-

    - name: Install Aqua
      uses: aquaproj/aqua-installer@5e54e5cee8a95ee2ce7c04cb993da6dfad13e59c # v3.2.1
      with:
        aqua_version: v2.48.1

    - name: Aqua Install
      shell: bash
      run: aqua install --tags ${{ inputs.tf_type }}

    - name: Configure AWS Credentials
      if: ${{ inputs.aws_role_arn != '' || env.TF_TEST_AWS_ROLE_ARN != '' }}
      uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 # v4.1.0
      with:
        role-to-assume: ${{ inputs.aws_role_arn || env.TF_TEST_AWS_ROLE_ARN }}
        role-session-name: ${{ inputs.role_session_name }}
        aws-region: ${{ inputs.aws_region }}

    - name: Run TF Test
      shell: bash
      run: |
        ${{ inputs.tf_type }} init
        ${{ inputs.tf_type }} test
